# Generated by Django 3.2.7 on 2021-09-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_phonedetail_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
