[{'country': 'Afghanistan', 'country_repr': 'AF', 'area_code': ['93']},
 {'country': 'Albania', 'country_repr': 'AL', 'area_code': ['355']},
 {'country': 'Algeria', 'country_repr': 'DZ', 'area_code': ['213']},
 {'country': 'American Samoa', 'country_repr': 'AS', 'area_code': ['1-684']},
 {'country': 'Andorra', 'country_repr': 'AD', 'area_code': ['376']},
 {'country': 'Angola', 'country_repr': 'AO', 'area_code': ['244']},
 {'country': 'Anguilla', 'country_repr': 'AI', 'area_code': ['1-264']},
 {'country': 'Antarctica', 'country_repr': 'AQ', 'area_code': ['672']},
 {'country': 'Antigua and Barbuda', 'country_repr': 'AG', 'area_code': ['1-268']},
 {'country': 'Argentina', 'country_repr': 'AR', 'area_code': ['54']},
 {'country': 'Armenia', 'country_repr': 'AM', 'area_code': ['374']},
 {'country': 'Aruba', 'country_repr': 'AW', 'area_code': ['297']},
 {'country': 'Australia', 'country_repr': 'AU', 'area_code': ['61']},
 {'country': 'Austria', 'country_repr': 'AT', 'area_code': ['43']},
 {'country': 'Azerbaijan', 'country_repr': 'AZ', 'area_code': ['994']},
 {'country': 'Bahamas', 'country_repr': 'BS', 'area_code': ['1-242']},
 {'country': 'Bahrain', 'country_repr': 'BH', 'area_code': ['973']},
 {'country': 'Bangladesh', 'country_repr': 'BD', 'area_code': ['880']},
 {'country': 'Barbados', 'country_repr': 'BB', 'area_code': ['1-246']},
 {'country': 'Belarus', 'country_repr': 'BY', 'area_code': ['375']},
 {'country': 'Belgium', 'country_repr': 'BE', 'area_code': ['32']},
 {'country': 'Belize', 'country_repr': 'BZ', 'area_code': ['501']},
 {'country': 'Benin', 'country_repr': 'BJ', 'area_code': ['229']},
 {'country': 'Bermuda', 'country_repr': 'BM', 'area_code': ['1-441']},
 {'country': 'Bhutan', 'country_repr': 'BT', 'area_code': ['975']},
 {'country': 'Bolivia', 'country_repr': 'BO', 'area_code': ['591']},
 {'country': 'Bosnia and Herzegovina', 'country_repr': 'BA', 'area_code': ['387']},
 {'country': 'Botswana', 'country_repr': 'BW', 'area_code': ['267']},
 {'country': 'Brazil', 'country_repr': 'BR', 'area_code': ['55']},
 {'country': 'British Indian Ocean Territory', 'country_repr': 'IO', 'area_code': ['246']},
 {'country': 'British Virgin Islands', 'country_repr': 'VG', 'area_code': ['1-284']},
 {'country': 'Brunei', 'country_repr': 'BN', 'area_code': ['673']},
 {'country': 'Bulgaria', 'country_repr': 'BG', 'area_code': ['359']},
 {'country': 'Burkina Faso', 'country_repr': 'BF', 'area_code': ['226']},
 {'country': 'Burundi', 'country_repr': 'BI', 'area_code': ['257']},
 {'country': 'Cambodia', 'country_repr': 'KH', 'area_code': ['855']},
 {'country': 'Cameroon', 'country_repr': 'CM', 'area_code': ['237']},
 {'country': 'Canada', 'country_repr': 'CA', 'area_code': ['1']},
 {'country': 'Cape Verde', 'country_repr': 'CV', 'area_code': ['238']},
 {'country': 'Cayman Islands', 'country_repr': 'KY', 'area_code': ['1-345']},
 {'country': 'Central African Republic', 'country_repr': 'CF', 'area_code': ['236']},
 {'country': 'Chad', 'country_repr': 'TD', 'area_code': ['235']},
 {'country': 'Chile', 'country_repr': 'CL', 'area_code': ['56']},
 {'country': 'China', 'country_repr': 'CN', 'area_code': ['86']},
 {'country': 'Christmas Island', 'country_repr': 'CX', 'area_code': ['61']},
 {'country': 'Cocos Islands', 'country_repr': 'CC', 'area_code': ['61']},
 {'country': 'Colombia', 'country_repr': 'CO', 'area_code': ['57']},
 {'country': 'Comoros', 'country_repr': 'KM', 'area_code': ['269']},
 {'country': 'Cook Islands', 'country_repr': 'CK', 'area_code': ['682']},
 {'country': 'Costa Rica', 'country_repr': 'CR', 'area_code': ['506']},
 {'country': 'Croatia', 'country_repr': 'HR', 'area_code': ['385']},
 {'country': 'Cuba', 'country_repr': 'CU', 'area_code': ['53']},
 {'country': 'Curacao', 'country_repr': 'CW', 'area_code': ['599']},
 {'country': 'Cyprus', 'country_repr': 'CY', 'area_code': ['357']},
 {'country': 'Czech Republic', 'country_repr': 'CZ', 'area_code': ['420']},
 {'country': 'Democratic Republic of the Congo', 'country_repr': 'CD', 'area_code': ['243']},
 {'country': 'Denmark', 'country_repr': 'DK', 'area_code': ['45']},
 {'country': 'Djibouti', 'country_repr': 'DJ', 'area_code': ['253']},
 {'country': 'Dominica', 'country_repr': 'DM', 'area_code': ['1-767']},
 {'country': 'Dominican Republic', 'country_repr': 'DO', 'area_code': ['1-809', '1-829', '1-849']},
 {'country': 'East Timor', 'country_repr': 'TL', 'area_code': ['670']},
 {'country': 'Ecuador', 'country_repr': 'EC', 'area_code': ['593']},
 {'country': 'Egypt', 'country_repr': 'EG', 'area_code': ['20']},
 {'country': 'El Salvador', 'country_repr': 'SV', 'area_code': ['503']},
 {'country': 'Equatorial Guinea', 'country_repr': 'GQ', 'area_code': ['240']},
 {'country': 'Eritrea', 'country_repr': 'ER', 'area_code': ['291']},
 {'country': 'Estonia', 'country_repr': 'EE', 'area_code': ['372']},
 {'country': 'Ethiopia', 'country_repr': 'ET', 'area_code': ['251']},
 {'country': 'Falkland Islands', 'country_repr': 'FK', 'area_code': ['500']},
 {'country': 'Faroe Islands', 'country_repr': 'FO', 'area_code': ['298']},
 {'country': 'Fiji', 'country_repr': 'FJ', 'area_code': ['679']},
 {'country': 'Finland', 'country_repr': 'FI', 'area_code': ['358']},
 {'country': 'France', 'country_repr': 'FR', 'area_code': ['33']},
 {'country': 'French Polynesia', 'country_repr': 'PF', 'area_code': ['689']},
 {'country': 'Gabon', 'country_repr': 'GA', 'area_code': ['241']},
 {'country': 'Gambia', 'country_repr': 'GM', 'area_code': ['220']},
 {'country': 'Georgia', 'country_repr': 'GE', 'area_code': ['995']},
 {'country': 'Germany', 'country_repr': 'DE', 'area_code': ['49']},
 {'country': 'Ghana', 'country_repr': 'GH', 'area_code': ['233']},
 {'country': 'Gibraltar', 'country_repr': 'GI', 'area_code': ['350']},
 {'country': 'Greece', 'country_repr': 'GR', 'area_code': ['30']},
 {'country': 'Greenland', 'country_repr': 'GL', 'area_code': ['299']},
 {'country': 'Grenada', 'country_repr': 'GD', 'area_code': ['1-473']},
 {'country': 'Guam', 'country_repr': 'GU', 'area_code': ['1-671']},
 {'country': 'Guatemala', 'country_repr': 'GT', 'area_code': ['502']},
 {'country': 'Guernsey', 'country_repr': 'GG', 'area_code': ['44-1481']},
 {'country': 'Guinea', 'country_repr': 'GN', 'area_code': ['224']},
 {'country': 'Guinea-Bissau', 'country_repr': 'GW', 'area_code': ['245']},
 {'country': 'Guyana', 'country_repr': 'GY', 'area_code': ['592']},
 {'country': 'Haiti', 'country_repr': 'HT', 'area_code': ['509']},
 {'country': 'Honduras', 'country_repr': 'HN', 'area_code': ['504']},
 {'country': 'Hong Kong', 'country_repr': 'HK', 'area_code': ['852']},
 {'country': 'Hungary', 'country_repr': 'HU', 'area_code': ['36']},
 {'country': 'Iceland', 'country_repr': 'IS', 'area_code': ['354']},
 {'country': 'India', 'country_repr': 'IN', 'area_code': ['91']},
 {'country': 'Indonesia', 'country_repr': 'ID', 'area_code': ['62']},
 {'country': 'Iran', 'country_repr': 'IR', 'area_code': ['98']},
 {'country': 'Iraq', 'country_repr': 'IQ', 'area_code': ['964']},
 {'country': 'Ireland', 'country_repr': 'IE', 'area_code': ['353']},
 {'country': 'Isle of Man', 'country_repr': 'IM', 'area_code': ['44-1624']},
 {'country': 'Israel', 'country_repr': 'IL', 'area_code': ['972']},
 {'country': 'Italy', 'country_repr': 'IT', 'area_code': ['39']},
 {'country': 'Ivory Coast', 'country_repr': 'CI', 'area_code': ['225']},
 {'country': 'Jamaica', 'country_repr': 'JM', 'area_code': ['1-876']},
 {'country': 'Japan', 'country_repr': 'JP', 'area_code': ['81']},
 {'country': 'Jersey', 'country_repr': 'JE', 'area_code': ['44-1534']},
 {'country': 'Jordan', 'country_repr': 'JO', 'area_code': ['962']},
 {'country': 'Kazakhstan', 'country_repr': 'KZ', 'area_code': ['7']},
 {'country': 'Kenya', 'country_repr': 'KE', 'area_code': ['254']},
 {'country': 'Kiribati', 'country_repr': 'KI', 'area_code': ['686']},
 {'country': 'Kosovo', 'country_repr': 'XK', 'area_code': ['Europe']},
 {'country': 'Kuwait', 'country_repr': 'KW', 'area_code': ['965']},
 {'country': 'Kyrgyzstan', 'country_repr': 'KG', 'area_code': ['996']},
 {'country': 'Laos', 'country_repr': 'LA', 'area_code': ['856']},
 {'country': 'Latvia', 'country_repr': 'LV', 'area_code': ['371']},
 {'country': 'Lebanon', 'country_repr': 'LB', 'area_code': ['961']},
 {'country': 'Lesotho', 'country_repr': 'LS', 'area_code': ['266']},
 {'country': 'Liberia', 'country_repr': 'LR', 'area_code': ['231']},
 {'country': 'Libya', 'country_repr': 'LY', 'area_code': ['218']},
 {'country': 'Liechtenstein', 'country_repr': 'LI', 'area_code': ['423']},
 {'country': 'Lithuania', 'country_repr': 'LT', 'area_code': ['370']},
 {'country': 'Luxembourg', 'country_repr': 'LU', 'area_code': ['352']},
 {'country': 'Macau', 'country_repr': 'MO', 'area_code': ['853']},
 {'country': 'Macedonia', 'country_repr': 'MK', 'area_code': ['389']},
 {'country': 'Madagascar', 'country_repr': 'MG', 'area_code': ['261']},
 {'country': 'Malawi', 'country_repr': 'MW', 'area_code': ['265']},
 {'country': 'Malaysia', 'country_repr': 'MY', 'area_code': ['60']},
 {'country': 'Maldives', 'country_repr': 'MV', 'area_code': ['960']},
 {'country': 'Mali', 'country_repr': 'ML', 'area_code': ['223']},
 {'country': 'Malta', 'country_repr': 'MT', 'area_code': ['356']},
 {'country': 'Marshall Islands', 'country_repr': 'MH', 'area_code': ['692']},
 {'country': 'Mauritania', 'country_repr': 'MR', 'area_code': ['222']},
 {'country': 'Mauritius', 'country_repr': 'MU', 'area_code': ['230']},
 {'country': 'Mayotte', 'country_repr': 'YT', 'area_code': ['262']},
 {'country': 'Mexico', 'country_repr': 'MX', 'area_code': ['52']},
 {'country': 'Micronesia', 'country_repr': 'FM', 'area_code': ['691']},
 {'country': 'Moldova', 'country_repr': 'MD', 'area_code': ['373']},
 {'country': 'Monaco', 'country_repr': 'MC', 'area_code': ['377']},
 {'country': 'Mongolia', 'country_repr': 'MN', 'area_code': ['976']},
 {'country': 'Montenegro', 'country_repr': 'ME', 'area_code': ['382']},
 {'country': 'Montserrat', 'country_repr': 'MS', 'area_code': ['1-664']},
 {'country': 'Morocco', 'country_repr': 'MA', 'area_code': ['212']},
 {'country': 'Mozambique', 'country_repr': 'MZ', 'area_code': ['258']},
 {'country': 'Myanmar', 'country_repr': 'MM', 'area_code': ['95']},
 {'country': 'Namibia', 'country_repr': 'NA', 'area_code': ['264']},
 {'country': 'Nauru', 'country_repr': 'NR', 'area_code': ['674']},
 {'country': 'Nepal', 'country_repr': 'NP', 'area_code': ['977']},
 {'country': 'Netherlands', 'country_repr': 'NL', 'area_code': ['31']},
 {'country': 'Netherlands Antilles', 'country_repr': 'AN', 'area_code': ['North America']},
 {'country': 'New Caledonia', 'country_repr': 'NC', 'area_code': ['687']},
 {'country': 'New Zealand', 'country_repr': 'NZ', 'area_code': ['64']},
 {'country': 'Nicaragua', 'country_repr': 'NI', 'area_code': ['505']},
 {'country': 'Niger', 'country_repr': 'NE', 'area_code': ['227']},
 {'country': 'Nigeria', 'country_repr': 'NG', 'area_code': ['234']},
 {'country': 'Niue', 'country_repr': 'NU', 'area_code': ['683']},
 {'country': 'North Korea', 'country_repr': 'KP', 'area_code': ['850']},
 {'country': 'Northern Mariana Islands', 'country_repr': 'MP', 'area_code': ['1-670']},
 {'country': 'Norway', 'country_repr': 'NO', 'area_code': ['47']},
 {'country': 'Oman', 'country_repr': 'OM', 'area_code': ['968']},
 {'country': 'Pakistan', 'country_repr': 'PK', 'area_code': ['92']},
 {'country': 'Palau', 'country_repr': 'PW', 'area_code': ['680']},
 {'country': 'Palestine', 'country_repr': 'PS', 'area_code': ['970']},
 {'country': 'Panama', 'country_repr': 'PA', 'area_code': ['507']},
 {'country': 'Papua New Guinea', 'country_repr': 'PG', 'area_code': ['675']},
 {'country': 'Paraguay', 'country_repr': 'PY', 'area_code': ['595']},
 {'country': 'Peru', 'country_repr': 'PE', 'area_code': ['51']},
 {'country': 'Philippines', 'country_repr': 'PH', 'area_code': ['63']},
 {'country': 'Pitcairn', 'country_repr': 'PN', 'area_code': ['64']},
 {'country': 'Poland', 'country_repr': 'PL', 'area_code': ['48']},
 {'country': 'Portugal', 'country_repr': 'PT', 'area_code': ['351']},
 {'country': 'Puerto Rico', 'country_repr': 'PR', 'area_code': ['1-787', '1-939']},
 {'country': 'Qatar', 'country_repr': 'QA', 'area_code': ['974']},
 {'country': 'Republic of the Congo', 'country_repr': 'CG', 'area_code': ['242']},
 {'country': 'Reunion', 'country_repr': 'RE', 'area_code': ['262']},
 {'country': 'Romania', 'country_repr': 'RO', 'area_code': ['40']},
 {'country': 'Russia', 'country_repr': 'RU', 'area_code': ['7']},
 {'country': 'Rwanda', 'country_repr': 'RW', 'area_code': ['250']},
 {'country': 'Saint Barthelemy', 'country_repr': 'BL', 'area_code': ['590']},
 {'country': 'Saint Helena', 'country_repr': 'SH', 'area_code': ['290']},
 {'country': 'Saint Kitts and Nevis', 'country_repr': 'KN', 'area_code': ['1-869']},
 {'country': 'Saint Lucia', 'country_repr': 'LC', 'area_code': ['1-758']},
 {'country': 'Saint Martin', 'country_repr': 'MF', 'area_code': ['590']},
 {'country': 'Saint Pierre and Miquelon', 'country_repr': 'PM', 'area_code': ['508']},
 {'country': 'Saint Vincent and the Grenadines', 'country_repr': 'VC', 'area_code': ['1-784']},
 {'country': 'Samoa', 'country_repr': 'WS', 'area_code': ['685']},
 {'country': 'San Marino', 'country_repr': 'SM', 'area_code': ['378']},
 {'country': 'Sao Tome and Principe', 'country_repr': 'ST', 'area_code': ['239']},
 {'country': 'Saudi Arabia', 'country_repr': 'SA', 'area_code': ['966']},
 {'country': 'Senegal', 'country_repr': 'SN', 'area_code': ['221']},
 {'country': 'Serbia', 'country_repr': 'RS', 'area_code': ['381']},
 {'country': 'Seychelles', 'country_repr': 'SC', 'area_code': ['248']},
 {'country': 'Sierra Leone', 'country_repr': 'SL', 'area_code': ['232']},
 {'country': 'Singapore', 'country_repr': 'SG', 'area_code': ['65']},
 {'country': 'Sint Maarten', 'country_repr': 'SX', 'area_code': ['1-721']},
 {'country': 'Slovakia', 'country_repr': 'SK', 'area_code': ['421']},
 {'country': 'Slovenia', 'country_repr': 'SI', 'area_code': ['386']},
 {'country': 'Solomon Islands', 'country_repr': 'SB', 'area_code': ['677']},
 {'country': 'Somalia', 'country_repr': 'SO', 'area_code': ['252']},
 {'country': 'South Africa', 'country_repr': 'ZA', 'area_code': ['27']},
 {'country': 'South Korea', 'country_repr': 'KR', 'area_code': ['82']},
 {'country': 'South Sudan', 'country_repr': 'SS', 'area_code': ['211']},
 {'country': 'Spain', 'country_repr': 'ES', 'area_code': ['34']},
 {'country': 'Sri Lanka', 'country_repr': 'LK', 'area_code': ['94']},
 {'country': 'Sudan', 'country_repr': 'SD', 'area_code': ['249']},
 {'country': 'Suriname', 'country_repr': 'SR', 'area_code': ['597']},
 {'country': 'Svalbard and Jan Mayen', 'country_repr': 'SJ', 'area_code': ['47']},
 {'country': 'Swaziland', 'country_repr': 'SZ', 'area_code': ['268']},
 {'country': 'Sweden', 'country_repr': 'SE', 'area_code': ['46']},
 {'country': 'Switzerland', 'country_repr': 'CH', 'area_code': ['41']},
 {'country': 'Syria', 'country_repr': 'SY', 'area_code': ['963']},
 {'country': 'Taiwan', 'country_repr': 'TW', 'area_code': ['886']},
 {'country': 'Tajikistan', 'country_repr': 'TJ', 'area_code': ['992']},
 {'country': 'Tanzania', 'country_repr': 'TZ', 'area_code': ['255']},
 {'country': 'Thailand', 'country_repr': 'TH', 'area_code': ['66']},
 {'country': 'Togo', 'country_repr': 'TG', 'area_code': ['228']},
 {'country': 'Tokelau', 'country_repr': 'TK', 'area_code': ['690']},
 {'country': 'Tonga', 'country_repr': 'TO', 'area_code': ['676']},
 {'country': 'Trinidad and Tobago', 'country_repr': 'TT', 'area_code': ['1-868']},
 {'country': 'Tunisia', 'country_repr': 'TN', 'area_code': ['216']},
 {'country': 'Turkey', 'country_repr': 'TR', 'area_code': ['90']},
 {'country': 'Turkmenistan', 'country_repr': 'TM', 'area_code': ['993']},
 {'country': 'Turks and Caicos Islands', 'country_repr': 'TC', 'area_code': ['1-649']},
 {'country': 'Tuvalu', 'country_repr': 'TV', 'area_code': ['688']},
 {'country': 'U.S. Virgin Islands', 'country_repr': 'VI', 'area_code': ['1-340']},
 {'country': 'Uganda', 'country_repr': 'UG', 'area_code': ['256']},
 {'country': 'Ukraine', 'country_repr': 'UA', 'area_code': ['380']},
 {'country': 'United Arab Emirates', 'country_repr': 'AE', 'area_code': ['971']},
 {'country': 'United Kingdom', 'country_repr': 'GB', 'area_code': ['44']},
 {'country': 'United States', 'country_repr': 'US', 'area_code': ['1']},
 {'country': 'Uruguay', 'country_repr': 'UY', 'area_code': ['598']},
 {'country': 'Uzbekistan', 'country_repr': 'UZ', 'area_code': ['998']},
 {'country': 'Vanuatu', 'country_repr': 'VU', 'area_code': ['678']},
 {'country': 'Vatican', 'country_repr': 'VA', 'area_code': ['379']},
 {'country': 'Venezuela', 'country_repr': 'VE', 'area_code': ['58']},
 {'country': 'Vietnam', 'country_repr': 'VN', 'area_code': ['84']},
 {'country': 'Wallis and Futuna', 'country_repr': 'WF', 'area_code': ['681']},
 {'country': 'Western Sahara', 'country_repr': 'EH', 'area_code': ['212']},
 {'country': 'Yemen', 'country_repr': 'YE', 'area_code': ['967']},
 {'country': 'Zambia', 'country_repr': 'ZM', 'area_code': ['260']},
 {'country': 'Zimbabwe', 'country_repr': 'ZW', 'area_code': ['263']}]
